version: '3.8'

networks:
  finance:
    name: financeBridge

    


services:

  backend: 
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    networks:
      - finance
    ports:
      - ${PORT_BACKEND}:${PORT_API}
    expose:
      - ${PORT_API}
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    
  frontend: 
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - finance
    ports:
      - ${PORT_FRONTEND}:${PORT_FRONTEND_INTERNAL}
    expose:
      - ${PORT_FRONTEND_INTERNAL}
    depends_on:
      - postgres
      - backend

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgressql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - finance
    expose:
      - ${POSTGRES_INTERNAL}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - finance

