# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ../postgres:/var/lib/postgressql/data
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080